### ISSUE TITLE
Naming using RFN

### ISSUE THREAD

**Issue by NightFurySL2001** [be5invis/source-han-sans-ttf#8]
Referencing [licensing terms](https://github.com/adobe-fonts/source-han-sans/blob/master/LICENSE.txt) in Source Han project, Source is a Reserved Font Name and future modified versions can not use Source as a font name.  
根据思源的[授权信息](https://github.com/adobe-fonts/source-han-sans/blob/master/LICENSE.txt)，Source 及 “思源” 两个词汇是保留字型名称，后期的衍生版本不可使用 Source 及 “思源” 作为字体名称。

**Comment by be5invis** [comment]
I implemented renaming (and now it is configurable). Resolved as fixed.
